SELECT 
    t.AUTHOR_ID,
    AUTHOR_NAME,
    CATEGORY,
    SUM(TOTAL_SALES) AS TOTAL_SALES
    FROM (
        SELECT 
            b.AUTHOR_ID,
            PRICE,
            CATEGORY,
            PRICE * SALES AS TOTAL_SALES
            FROM BOOK b
        JOIN (
            SELECT BOOK_ID, SALES FROM BOOK_SALES
            WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
        ) AS s ON b.BOOK_ID = s.BOOK_ID
    ) AS t
JOIN AUTHOR a ON t.AUTHOR_ID = a.AUTHOR_ID
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;
