SELECT MEMBER_NAME, REVIEW_TEXT,
       DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
       FROM REST_REVIEW r
JOIN (
    SELECT t1.MEMBER_ID, CNT FROM (
        SELECT MEMBER_ID, COUNT(*) AS CNT FROM REST_REVIEW
        GROUP BY MEMBER_ID
    ) AS t1
    JOIN (
        SELECT MEMBER_ID, MAX(CNT) AS MAX_CNT FROM (
            SELECT MEMBER_ID, COUNT(*) AS CNT FROM REST_REVIEW
            GROUP BY MEMBER_ID) AS temp
    ) AS t2
    ON t1.CNT = t2.MAX_CNT
) AS t3 
ON r.MEMBER_ID = t3.MEMBER_ID
JOIN MEMBER_PROFILE p ON r.MEMBER_ID = p.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT;
