SELECT 
    fo.PRODUCT_ID,
    PRODUCT_NAME,
    fp.PRICE * fo.AMOUNT AS TOTAL_SALES
FROM (SELECT 
        PRODUCT_ID,
        SUM(AMOUNT) AS AMOUNT
      FROM FOOD_ORDER
      WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
      GROUP BY PRODUCT_ID) AS fo
JOIN FOOD_PRODUCT fp ON fo.PRODUCT_ID = fp.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;
