SELECT f_p.CATEGORY, f_p.PRICE AS MAX_PRICE, f_p.PRODUCT_NAME FROM 
(
    SELECT CATEGORY, MAX(PRICE) AS PRICE FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) AS temp
INNER JOIN FOOD_PRODUCT f_p 
ON f_p.CATEGORY = temp.CATEGORY AND temp.PRICE = f_p.PRICE
WHERE f_p.CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY, MAX_PRICE
ORDER BY MAX_PRICE DESC;
