SELECT 
    rr.REST_ID,
    REST_NAME,
    FOOD_TYPE,
    FAVORITES,
    ADDRESS,
    SCORE
    FROM REST_INFO ri
RIGHT JOIN (SELECT 
                REST_ID, 
                ROUND(AVG(REVIEW_SCORE), 2) AS SCORE 
            FROM REST_REVIEW
            GROUP BY REST_ID) AS rr
ON ri.REST_ID = rr.REST_ID
WHERE LEFT(ADDRESS, 2) = '서울'
ORDER BY SCORE DESC, FAVORITES DESC;
