-- 서브쿼리 조인절을 통한 GROUP BY 내에서 최대 값 컬럼을 찾는 쿼리

SELECT r.FOOD_TYPE, r.REST_ID, r.REST_NAME, r.FAVORITES 
FROM (
    SELECT FOOD_TYPE, MAX(FAVORITES) MAX_FAVORITES FROM REST_INFO GROUP BY FOOD_TYPE
    ) as x
INNER JOIN REST_INFO r on r.FOOD_TYPE = x.FOOD_TYPE and r.FAVORITES = x.MAX_FAVORITES
ORDER BY FOOD_TYPE DESC;
