CREATE TABLE BOOK (
    BOOK_ID INTEGER NOT NULL,
    CATEGORY VARCHAR(255) NOT NULL,
    AUTHOR_ID INTEGER NOT NULL,
    PRICE INTEGER NOT NULL,
    PUBLISHED_DATE DATE NOT NULL,
    PRIMARY KEY (BOOK_ID)
);

CREATE TABLE AUTHOR (
    AUTHOR_ID INTEGER NOT NULL,
    AUTHOR_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (AUTHOR_ID)
);

INSERT BOOK (BOOK_ID, CATEGORY, AUTHOR_ID, PRICE, PUBLISHED_DATE)
VALUES (1, '인문', 1, 10000, '2020-01-01'),
       (2, '경제', 1, 9000, '2021-04-11'),
       (3, '경제', 2, 11000, '2021-02-05');

INSERT AUTHOR (AUTHOR_ID, AUTHOR_NAME)
VALUES (1, '홍길동'),
       (2, '김영호');

-- DATE_FORMAT 함수를 통해 Date 타입을 String으로 형식을 원하는 데로 바꿀 수 있다.
SELECT BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') FROM BOOK
    left join AUTHOR A on BOOK.AUTHOR_ID = A.AUTHOR_ID
    where CATEGORY='경제'
    order by PUBLISHED_DATE;