SELECT 
    PRODUCT_CODE,
    PRICE * SALES_AMOUNT AS SALES
    FROM (
        SELECT p.PRODUCT_ID, p.PRODUCT_CODE, p.PRICE, o.SALES_AMOUNT FROM PRODUCT p
        JOIN 
            (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT FROM OFFLINE_SALE
            GROUP BY PRODUCT_ID) AS o
        ON p.PRODUCT_ID = o.PRODUCT_ID
    ) AS t
ORDER BY SALES DESC, PRODUCT_CODE;
