SELECT CAR_TYPE, COUNT(CAR_TYPE) AS CARS FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE CONCAT('%', '통풍', '%') OR OPTIONS LIKE CONCAT('%', '열선시트', '%') OR OPTIONS LIKE CONCAT('%', '가죽시트', '%')
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE, COUNT(CAR_TYPE) DESC;

-- 정규표현식(REGEXP)를 사용한 또 다른 방법
SELECT CAR_TYPE, COUNT(CAR_TYPE) AS CARS FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS REGEXP ('통풍시트|열선시트|가죽시트')
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE, COUNT(CAR_TYPE) DESC;